debug = true
logLevel = "DEBUG"

defaultEntryPoints = ["https", "http"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"

    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "../dump/private/astronomer.ullaakut.eu.crt"
      keyFile = "../dump/certs/astronomer.ullaakut.eu.key"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "ullaakut.eu"
watch = true
exposedByDefault = false

[acme]
acmeLogging = true
email = "brendan.le-glaunec@epitech.eu"
storage = "acme.json"
entryPoint = "https"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
    [acme.httpChallenge]
    entryPoint = "http"